FROM php:8.3-cli

WORKDIR /app

# Instala paquetes del sistema y extensiones necesarias de PHP
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    zip \
    libzip-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libicu-dev \
    libpq-dev \
    default-mysql-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        bcmath \
        exif \
        gd \
        intl \
        mbstring \
        pcntl \
        zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instala Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copia primero composer para aprovechar cache
COPY composer.json composer.lock ./

# Instala dependencias PHP
RUN composer install \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --no-dev

# Copia el resto del proyecto
COPY . .

# Permisos y script de arranque
RUN chmod -R 775 storage bootstrap/cache \
    && chmod +x /app/start.sh

EXPOSE 8000

CMD ["/app/start.sh"]